before_script:
  - apt-get update -qq & apt-get install -y  -qq nodejs
  - node -v 
  - apt-get update -qq && apt-get install -y -qq yarn
  - yarn -v 

build:
  script:
  - yarn install
  - yarn build

serve: 
  script:
  - yarn add global serve
  - serve -s build
